blank_issues_enabled: true
contact_links:
  - name: Feature Proposals
    url: https://github.com/pyscript/packages/discussions/new?category=proposals
    about: Create a feature request to make pyscript packages even better
  - name: Questions & Help
    url: https://github.com/pyscript/packages/discussions/new?category=q-a
    about: For questions or discussions about pyscript packages